### ISSUE TITLE
Permissions Problem

### ISSUE THREAD

**Issue by GoT-HiM** [Jakubson/JPremium#4]
The error is as follows. When I put the Main server associated with Main and the Limbo server always associated with Main, Luckperms deletes the users and recreates them with every quit and join.

**Comment by Jakubson** [comment]
Hi, I do not often visit issues on Github. I am sorry that I reply so late. JPremium is not longer supported. Only JPremium Cleared is supported.
I have only on SpigotMC, so if you have issues, please write DM on SpigotMC: https://www.spigotmc.org/conversations/add?to=Jakubson and then I will solve all of your issues and reply for all of your questions.
